name: Create Release

on:
  push:
    tags:
      - 'v*.*.*' # Triggers the workflow on version tags

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Create ZIP file
        run: |
          zip -r BlurChat.zip . -x "assets/chat-ss.jpeg" -x "assets/home-ss.jpeg" -x "README.md"

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ## Changes in this release
            - Initial release of BlurChat extension.
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./BlurChat.zip
          asset_name: BlurChat.zip
          asset_content_type: application/zip
